### ISSUE TITLE
Cornershop API Documentation

### ISSUE THREAD

**Issue by es-eph** [GusFurtado/cornershop#1]
Hello Gus, hope you are doing fine. 

I was wondering if you could tell me where did you get the url's to call the Cornershop API. Is there any documentation on the API that I could refer in order to know how to use them? I can't seem to find it online. 

Thanks in advance.

Muito obrigado! :)

**Comment by GusFurtado** [comment]
Hi, sferrando89.

I found the URL using the browser's element inspector. It is an internal Cornershop API used to feed their website.

This package is basically a scraper, so it can't get any more unofficial than that. Their API has no official documentation, because it is not intended as a developer tool. 

Let me know If there is anything I can help.
